 - hosts: all
   vars:
    wp_version: 4.0
    wp_install_dir: '/var/www/html'
    wp_db_name: 'database_name_here'
    wp_db_user: 'username_here'
    wp_db_password: 'password_here'
    wp_db_host: 'localhost'
  roles:
  - wordpress
